# handlers file for balance
# - name: restart haproxy
#   systemd:
#     name: haproxy
#     state: restarted
#     enabled: yes
- name: restart postgres
  service: name=postgresql state=restarted
- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
